# Generated by Django 2.2.6 on 2019-10-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LNMOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=20, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.CharField(blank=True, max_length=200)),
                ('saccess_amount', models.FloatField(blank=True, null=True)),
                ('saccess_mpesa_receipt_number', models.CharField(blank=True, max_length=20)),
                ('saccess_transaction_date', models.CharField(blank=True, max_length=20)),
                ('saccess_balance', models.FloatField(blank=True, max_length=10, null=True)),
                ('saccess_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('success_result_description', models.CharField(blank=True, max_length=150)),
                ('fail_result_description', models.CharField(blank=True, max_length=150)),
                ('fail_merchant_request_id', models.CharField(blank=True, max_length=150)),
                ('fail_result_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
