# Generated by Django 2.2.6 on 2019-10-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_userhostelplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhostelplan',
            old_name='user',
            new_name='tenant',
        ),
    ]
