# Generated by Django 2.2.6 on 2019-10-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20191023_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhostelplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landloard.HostelPlan'),
        ),
    ]
