# Generated by Django 2.2.6 on 2019-10-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_auto_20191031_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomateselection',
            old_name='is_selected',
            new_name='is_accepted',
        ),
    ]
