# Generated by Django 2.2.6 on 2019-10-20 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=191)),
                ('hostel_location', models.CharField(blank=True, max_length=191, null=True)),
                ('your_full_name', models.CharField(blank=True, max_length=191, null=True)),
                ('your_phone_number', models.CharField(blank=True, max_length=191, null=True)),
                ('your_picture', models.ImageField(upload_to='landlord')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostelService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.TextField()),
                ('water_supply', models.TextField()),
                ('power_supply', models.TextField()),
                ('bed_size', models.TextField()),
                ('room_size', models.TextField()),
                ('table_and_chair_availabitity', models.TextField()),
                ('total_no_of_rooms', models.CharField(blank=True, max_length=191, null=True)),
                ('hostel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landloard.LandlordProfile')),
            ],
        ),
        migrations.CreateModel(
            name='HostelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_room_desc', models.TextField(blank=True, null=True)),
                ('single_room_payment_price', models.CharField(blank=True, max_length=12, null=True)),
                ('double_room_payment_price', models.CharField(blank=True, max_length=12, null=True)),
                ('double_room_desc', models.TextField(blank=True, null=True)),
                ('self_contained', models.TextField(blank=True, null=True)),
                ('mpesa_shotcode', models.CharField(blank=True, max_length=12, null=True)),
                ('self_contained_payment_price', models.CharField(blank=True, max_length=12, null=True)),
                ('hostel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landloard.LandlordProfile')),
            ],
        ),
        migrations.CreateModel(
            name='HostelHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcoming_message', models.TextField()),
                ('background_image', models.ImageField(upload_to='hostel_homepages')),
                ('hostel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landloard.LandlordProfile')),
            ],
        ),
        migrations.CreateModel(
            name='HostelGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_description', models.TextField()),
                ('photo', models.ImageField(upload_to='Hostel_gallery')),
                ('hostel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landloard.LandlordProfile')),
            ],
        ),
        migrations.CreateModel(
            name='HostelContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_phone_number', models.CharField(max_length=20)),
                ('hostel_mail', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(blank=True, max_length=191, null=True)),
                ('hostel_address', models.TextField()),
                ('hostel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landloard.LandlordProfile')),
            ],
        ),
    ]
